import type { RatingAttribute } from './types'

// Season is derived from the current year so labels never need manual updates.
export const CURRENT_SEASON = new Date().getFullYear()
export const SEASON_LABEL = `SEASON ${CURRENT_SEASON}`

// Skill attributes teammates rate each other on (1-10), shown FIFA-style.
export const RATING_ATTRIBUTES: { key: RatingAttribute; label: string }[] = [
  { key: 'pace', label: 'PACE' },
  { key: 'shooting', label: 'SHOOTING' },
  { key: 'passing', label: 'PASSING' },
  { key: 'dribbling', label: 'DRIBBLING' },
  { key: 'defending', label: 'DEFENDING' },
  { key: 'physical', label: 'PHYSICAL' },
]

// FIFA-style trait badges players can be tagged with (separate from the
// 6 teammate-rated attributes above).
export const TRAITS: { id: string; label: string }[] = [
  { id: 'finisher', label: 'FINISHER' },
  { id: 'engine', label: 'ENGINE' },
  { id: 'speedster', label: 'SPEEDSTER' },
  { id: 'playmaker', label: 'PLAYMAKER' },
  { id: 'aerial-threat', label: 'AERIAL THREAT' },
  { id: 'tackler', label: 'TACKLER' },
  { id: 'distributor', label: 'DISTRIBUTOR' },
  { id: 'leader', label: 'LEADER' },
  { id: 'wall', label: 'WALL' },
  { id: 'showboat', label: 'SHOWBOAT' },
  { id: 'workhorse', label: 'WORKHORSE' },
  { id: 'sniper', label: 'SNIPER' },
  { id: 'clutch', label: 'CLUTCH' },
  { id: 'enforcer', label: 'ENFORCER' },
]

export function getTrait(id: string) {
  return TRAITS.find((t) => t.id === id)
}

export interface Club {
  id: string
  name: string
  file: string
}

// Badge PNGs live in /public/runitback/badges/<file>, sourced from
// https://github.com/luukhopman/football-logos
export const CLUBS: Club[] = [
  // Austria - Bundesliga
  { id: 'austria-vienna', name: 'Austria Vienna', file: 'austria-vienna.png' },
  { id: 'fc-blau-weiss-linz', name: 'FC Blau-Weiss Linz', file: 'fc-blau-weiss-linz.png' },
  { id: 'grazer-ak-1902', name: 'Grazer AK 1902', file: 'grazer-ak-1902.png' },
  { id: 'lask', name: 'LASK', file: 'lask.png' },
  { id: 'rapid-vienna', name: 'Rapid Vienna', file: 'rapid-vienna.png' },
  { id: 'red-bull-salzburg', name: 'Red Bull Salzburg', file: 'red-bull-salzburg.png' },
  { id: 'scr-altach', name: 'SCR Altach', file: 'scr-altach.png' },
  { id: 'sk-sturm-graz', name: 'SK Sturm Graz', file: 'sk-sturm-graz.png' },
  { id: 'sv-ried', name: 'SV Ried', file: 'sv-ried.png' },
  { id: 'tsv-hartberg', name: 'TSV Hartberg', file: 'tsv-hartberg.png' },
  { id: 'wsg-tirol', name: 'WSG Tirol', file: 'wsg-tirol.png' },
  { id: 'wolfsberger-ac', name: 'Wolfsberger AC', file: 'wolfsberger-ac.png' },
  // Belgium - Jupiler Pro League
  { id: 'cercle-brugge', name: 'Cercle Brugge', file: 'cercle-brugge.png' },
  { id: 'club-brugge-kv', name: 'Club Brugge KV', file: 'club-brugge-kv.png' },
  { id: 'fcv-dender-eh', name: 'FCV Dender EH', file: 'fcv-dender-eh.png' },
  { id: 'kaa-gent', name: 'KAA Gent', file: 'kaa-gent.png' },
  { id: 'krc-genk', name: 'KRC Genk', file: 'krc-genk.png' },
  { id: 'kv-mechelen', name: 'KV Mechelen', file: 'kv-mechelen.png' },
  { id: 'kvc-westerlo', name: 'KVC Westerlo', file: 'kvc-westerlo.png' },
  { id: 'oud-heverlee-leuven', name: 'Oud-Heverlee Leuven', file: 'oud-heverlee-leuven.png' },
  { id: 'raal-la-louviere', name: 'RAAL La Louvière', file: 'raal-la-louviere.png' },
  { id: 'rsc-anderlecht', name: 'RSC Anderlecht', file: 'rsc-anderlecht.png' },
  { id: 'royal-antwerp-fc', name: 'Royal Antwerp FC', file: 'royal-antwerp-fc.png' },
  { id: 'royal-charleroi-sc', name: 'Royal Charleroi SC', file: 'royal-charleroi-sc.png' },
  { id: 'sint-truidense-vv', name: 'Sint-Truidense VV', file: 'sint-truidense-vv.png' },
  { id: 'standard-liege', name: 'Standard Liège', file: 'standard-liege.png' },
  { id: 'union-saint-gilloise', name: 'Union Saint-Gilloise', file: 'union-saint-gilloise.png' },
  { id: 'zulte-waregem', name: 'Zulte Waregem', file: 'zulte-waregem.png' },
  // Bulgaria - efbet Liga
  { id: 'arda-kardzhali', name: 'Arda Kardzhali', file: 'arda-kardzhali.png' },
  { id: 'beroe-stara-zagora', name: 'Beroe Stara Zagora', file: 'beroe-stara-zagora.png' },
  { id: 'botev-plovdiv', name: 'Botev Plovdiv', file: 'botev-plovdiv.png' },
  { id: 'botev-vratsa', name: 'Botev Vratsa', file: 'botev-vratsa.png' },
  { id: 'cska-1948', name: 'CSKA 1948', file: 'cska-1948.png' },
  { id: 'cska-sofia', name: 'CSKA-Sofia', file: 'cska-sofia.png' },
  { id: 'cherno-more-varna', name: 'Cherno More Varna', file: 'cherno-more-varna.png' },
  { id: 'dobrudzha-dobrich', name: 'Dobrudzha Dobrich', file: 'dobrudzha-dobrich.png' },
  { id: 'levski-sofia', name: 'Levski Sofia', file: 'levski-sofia.png' },
  { id: 'lokomotiv-plovdiv', name: 'Lokomotiv Plovdiv', file: 'lokomotiv-plovdiv.png' },
  { id: 'lokomotiv-sofia', name: 'Lokomotiv Sofia', file: 'lokomotiv-sofia.png' },
  { id: 'ludogorets-razgrad', name: 'Ludogorets Razgrad', file: 'ludogorets-razgrad.png' },
  { id: 'montana', name: 'Montana', file: 'montana.png' },
  { id: 'septemvri-sofia', name: 'Septemvri Sofia', file: 'septemvri-sofia.png' },
  { id: 'slavia-sofia', name: 'Slavia Sofia', file: 'slavia-sofia.png' },
  { id: 'spartak-varna', name: 'Spartak Varna', file: 'spartak-varna.png' },
  // Croatia - SuperSport HNL
  { id: 'gnk-dinamo-zagreb', name: 'GNK Dinamo Zagreb', file: 'gnk-dinamo-zagreb.png' },
  { id: 'hnk-gorica', name: 'HNK Gorica', file: 'hnk-gorica.png' },
  { id: 'hnk-hajduk-split', name: 'HNK Hajduk Split', file: 'hnk-hajduk-split.png' },
  { id: 'hnk-rijeka', name: 'HNK Rijeka', file: 'hnk-rijeka.png' },
  { id: 'hnk-vukovar-1991', name: 'HNK Vukovar 1991', file: 'hnk-vukovar-1991.png' },
  { id: 'nk-istra-1961', name: 'NK Istra 1961', file: 'nk-istra-1961.png' },
  { id: 'nk-lokomotiva-zagreb', name: 'NK Lokomotiva Zagreb', file: 'nk-lokomotiva-zagreb.png' },
  { id: 'nk-osijek', name: 'NK Osijek', file: 'nk-osijek.png' },
  { id: 'nk-varazdin', name: 'NK Varazdin', file: 'nk-varazdin.png' },
  { id: 'slaven-belupo-koprivnica', name: 'Slaven Belupo Koprivnica', file: 'slaven-belupo-koprivnica.png' },
  // Czech Republic - Chance Liga
  { id: '1-fc-slovacko', name: '1.FC Slovacko', file: '1-fc-slovacko.png' },
  { id: 'ac-sparta-prague', name: 'AC Sparta Prague', file: 'ac-sparta-prague.png' },
  { id: 'bohemians-prague-1905', name: 'Bohemians Prague 1905', file: 'bohemians-prague-1905.png' },
  { id: 'fc-banik-ostrava', name: 'FC Banik Ostrava', file: 'fc-banik-ostrava.png' },
  { id: 'fc-hradec-kralove', name: 'FC Hradec Kralove', file: 'fc-hradec-kralove.png' },
  { id: 'fc-slovan-liberec', name: 'FC Slovan Liberec', file: 'fc-slovan-liberec.png' },
  { id: 'fc-viktoria-plzen', name: 'FC Viktoria Plzen', file: 'fc-viktoria-plzen.png' },
  { id: 'fc-zlin', name: 'FC Zlin', file: 'fc-zlin.png' },
  { id: 'fk-dukla-prague', name: 'FK Dukla Prague', file: 'fk-dukla-prague.png' },
  { id: 'fk-jablonec', name: 'FK Jablonec', file: 'fk-jablonec.png' },
  { id: 'fk-mlada-boleslav', name: 'FK Mlada Boleslav', file: 'fk-mlada-boleslav.png' },
  { id: 'fk-pardubice', name: 'FK Pardubice', file: 'fk-pardubice.png' },
  { id: 'fk-teplice', name: 'FK Teplice', file: 'fk-teplice.png' },
  { id: 'mfk-karvina', name: 'MFK Karvina', file: 'mfk-karvina.png' },
  { id: 'sk-sigma-olomouc', name: 'SK Sigma Olomouc', file: 'sk-sigma-olomouc.png' },
  { id: 'sk-slavia-prague', name: 'SK Slavia Prague', file: 'sk-slavia-prague.png' },
  // Denmark - Superliga
  { id: 'aarhus-gf', name: 'Aarhus GF', file: 'aarhus-gf.png' },
  { id: 'brondby-if', name: 'Bröndby IF', file: 'brondby-if.png' },
  { id: 'fc-copenhagen', name: 'FC Copenhagen', file: 'fc-copenhagen.png' },
  { id: 'fc-fredericia', name: 'FC Fredericia', file: 'fc-fredericia.png' },
  { id: 'fc-midtjylland', name: 'FC Midtjylland', file: 'fc-midtjylland.png' },
  { id: 'fc-nordsjaelland', name: 'FC Nordsjaelland', file: 'fc-nordsjaelland.png' },
  { id: 'odense-boldklub', name: 'Odense Boldklub', file: 'odense-boldklub.png' },
  { id: 'randers-fc', name: 'Randers FC', file: 'randers-fc.png' },
  { id: 'silkeborg-if', name: 'Silkeborg IF', file: 'silkeborg-if.png' },
  { id: 'sonderjyske', name: 'Sönderjyske', file: 'sonderjyske.png' },
  { id: 'vejle-boldklub', name: 'Vejle Boldklub', file: 'vejle-boldklub.png' },
  { id: 'viborg-ff', name: 'Viborg FF', file: 'viborg-ff.png' },
  // England - Premier League
  { id: 'afc-bournemouth', name: 'AFC Bournemouth', file: 'afc-bournemouth.png' },
  { id: 'arsenal-fc', name: 'Arsenal FC', file: 'arsenal-fc.png' },
  { id: 'aston-villa', name: 'Aston Villa', file: 'aston-villa.png' },
  { id: 'brentford-fc', name: 'Brentford FC', file: 'brentford-fc.png' },
  { id: 'brighton-hove-albion', name: 'Brighton & Hove Albion', file: 'brighton-hove-albion.png' },
  { id: 'burnley-fc', name: 'Burnley FC', file: 'burnley-fc.png' },
  { id: 'chelsea-fc', name: 'Chelsea FC', file: 'chelsea-fc.png' },
  { id: 'crystal-palace', name: 'Crystal Palace', file: 'crystal-palace.png' },
  { id: 'everton-fc', name: 'Everton FC', file: 'everton-fc.png' },
  { id: 'fulham-fc', name: 'Fulham FC', file: 'fulham-fc.png' },
  { id: 'leeds-united', name: 'Leeds United', file: 'leeds-united.png' },
  { id: 'liverpool-fc', name: 'Liverpool FC', file: 'liverpool-fc.png' },
  { id: 'manchester-city', name: 'Manchester City', file: 'manchester-city.png' },
  { id: 'manchester-united', name: 'Manchester United', file: 'manchester-united.png' },
  { id: 'newcastle-united', name: 'Newcastle United', file: 'newcastle-united.png' },
  { id: 'nottingham-forest', name: 'Nottingham Forest', file: 'nottingham-forest.png' },
  { id: 'sunderland-afc', name: 'Sunderland AFC', file: 'sunderland-afc.png' },
  { id: 'tottenham-hotspur', name: 'Tottenham Hotspur', file: 'tottenham-hotspur.png' },
  { id: 'west-ham-united', name: 'West Ham United', file: 'west-ham-united.png' },
  { id: 'wolverhampton-wanderers', name: 'Wolverhampton Wanderers', file: 'wolverhampton-wanderers.png' },
  // France - Ligue 1
  { id: 'aj-auxerre', name: 'AJ Auxerre', file: 'aj-auxerre.png' },
  { id: 'as-monaco', name: 'AS Monaco', file: 'as-monaco.png' },
  { id: 'angers-sco', name: 'Angers SCO', file: 'angers-sco.png' },
  { id: 'fc-lorient', name: 'FC Lorient', file: 'fc-lorient.png' },
  { id: 'fc-metz', name: 'FC Metz', file: 'fc-metz.png' },
  { id: 'fc-nantes', name: 'FC Nantes', file: 'fc-nantes.png' },
  { id: 'fc-toulouse', name: 'FC Toulouse', file: 'fc-toulouse.png' },
  { id: 'losc-lille', name: 'LOSC Lille', file: 'losc-lille.png' },
  { id: 'le-havre-ac', name: 'Le Havre AC', file: 'le-havre-ac.png' },
  { id: 'ogc-nice', name: 'OGC Nice', file: 'ogc-nice.png' },
  { id: 'olympique-lyon', name: 'Olympique Lyon', file: 'olympique-lyon.png' },
  { id: 'olympique-marseille', name: 'Olympique Marseille', file: 'olympique-marseille.png' },
  { id: 'paris-fc', name: 'Paris FC', file: 'paris-fc.png' },
  { id: 'paris-saint-germain', name: 'Paris Saint-Germain', file: 'paris-saint-germain.png' },
  { id: 'rc-lens', name: 'RC Lens', file: 'rc-lens.png' },
  { id: 'rc-strasbourg-alsace', name: 'RC Strasbourg Alsace', file: 'rc-strasbourg-alsace.png' },
  { id: 'stade-brestois-29', name: 'Stade Brestois 29', file: 'stade-brestois-29.png' },
  { id: 'stade-rennais-fc', name: 'Stade Rennais FC', file: 'stade-rennais-fc.png' },
  // Germany - Bundesliga
  { id: '1-fc-heidenheim-1846', name: '1.FC Heidenheim 1846', file: '1-fc-heidenheim-1846.png' },
  { id: '1-fc-koln', name: '1.FC Köln', file: '1-fc-koln.png' },
  { id: '1-fc-union-berlin', name: '1.FC Union Berlin', file: '1-fc-union-berlin.png' },
  { id: '1-fsv-mainz-05', name: '1.FSV Mainz 05', file: '1-fsv-mainz-05.png' },
  { id: 'bayer-04-leverkusen', name: 'Bayer 04 Leverkusen', file: 'bayer-04-leverkusen.png' },
  { id: 'bayern-munich', name: 'Bayern Munich', file: 'bayern-munich.png' },
  { id: 'borussia-dortmund', name: 'Borussia Dortmund', file: 'borussia-dortmund.png' },
  { id: 'borussia-monchengladbach', name: 'Borussia Mönchengladbach', file: 'borussia-monchengladbach.png' },
  { id: 'eintracht-frankfurt', name: 'Eintracht Frankfurt', file: 'eintracht-frankfurt.png' },
  { id: 'fc-augsburg', name: 'FC Augsburg', file: 'fc-augsburg.png' },
  { id: 'fc-st-pauli', name: 'FC St. Pauli', file: 'fc-st-pauli.png' },
  { id: 'hamburger-sv', name: 'Hamburger SV', file: 'hamburger-sv.png' },
  { id: 'rb-leipzig', name: 'RB Leipzig', file: 'rb-leipzig.png' },
  { id: 'sc-freiburg', name: 'SC Freiburg', file: 'sc-freiburg.png' },
  { id: 'sv-werder-bremen', name: 'SV Werder Bremen', file: 'sv-werder-bremen.png' },
  { id: 'tsg-1899-hoffenheim', name: 'TSG 1899 Hoffenheim', file: 'tsg-1899-hoffenheim.png' },
  { id: 'vfb-stuttgart', name: 'VfB Stuttgart', file: 'vfb-stuttgart.png' },
  { id: 'vfl-wolfsburg', name: 'VfL Wolfsburg', file: 'vfl-wolfsburg.png' },
  // Greece - Super League 1
  { id: 'ae-kifisias', name: 'AE Kifisias', file: 'ae-kifisias.png' },
  { id: 'ae-larisa', name: 'AE Larisa', file: 'ae-larisa.png' },
  { id: 'aek-athens', name: 'AEK Athens', file: 'aek-athens.png' },
  { id: 'apo-levadiakos', name: 'APO Levadiakos', file: 'apo-levadiakos.png' },
  { id: 'aris-thessaloniki', name: 'Aris Thessaloniki', file: 'aris-thessaloniki.png' },
  { id: 'asteras-aktor', name: 'Asteras Aktor', file: 'asteras-aktor.png' },
  { id: 'atromitos-athens', name: 'Atromitos Athens', file: 'atromitos-athens.png' },
  { id: 'ofi-crete-fc', name: 'OFI Crete FC', file: 'ofi-crete-fc.png' },
  { id: 'olympiacos-piraeus', name: 'Olympiacos Piraeus', file: 'olympiacos-piraeus.png' },
  { id: 'paok-thessaloniki', name: 'PAOK Thessaloniki', file: 'paok-thessaloniki.png' },
  { id: 'panathinaikos-fc', name: 'Panathinaikos FC', file: 'panathinaikos-fc.png' },
  { id: 'panetolikos-gfs', name: 'Panetolikos GFS', file: 'panetolikos-gfs.png' },
  { id: 'panserraikos', name: 'Panserraikos', file: 'panserraikos.png' },
  { id: 'volos-nps', name: 'Volos NPS', file: 'volos-nps.png' },
  // Israel - Ligat ha'Al
  { id: 'beitar-jerusalem', name: 'Beitar Jerusalem', file: 'beitar-jerusalem.png' },
  { id: 'fc-ashdod', name: 'FC Ashdod', file: 'fc-ashdod.png' },
  { id: 'hapoel-beer-sheva', name: 'Hapoel Beer Sheva', file: 'hapoel-beer-sheva.png' },
  { id: 'hapoel-haifa', name: 'Hapoel Haifa', file: 'hapoel-haifa.png' },
  { id: 'hapoel-jerusalem', name: 'Hapoel Jerusalem', file: 'hapoel-jerusalem.png' },
  { id: 'hapoel-petah-tikva', name: 'Hapoel Petah Tikva', file: 'hapoel-petah-tikva.png' },
  { id: 'hapoel-tel-aviv', name: 'Hapoel Tel Aviv', file: 'hapoel-tel-aviv.png' },
  { id: 'ihud-bnei-sakhnin', name: 'Ihud Bnei Sakhnin', file: 'ihud-bnei-sakhnin.png' },
  { id: 'ironi-kiryat-shmona', name: 'Ironi Kiryat Shmona', file: 'ironi-kiryat-shmona.png' },
  { id: 'ironi-tiberias', name: 'Ironi Tiberias', file: 'ironi-tiberias.png' },
  { id: 'maccabi-bnei-reineh', name: 'Maccabi Bnei Reineh', file: 'maccabi-bnei-reineh.png' },
  { id: 'maccabi-haifa', name: 'Maccabi Haifa', file: 'maccabi-haifa.png' },
  { id: 'maccabi-netanya', name: 'Maccabi Netanya', file: 'maccabi-netanya.png' },
  { id: 'maccabi-tel-aviv', name: 'Maccabi Tel Aviv', file: 'maccabi-tel-aviv.png' },
  // Italy - Serie A
  { id: 'ac-milan', name: 'AC Milan', file: 'ac-milan.png' },
  { id: 'acf-fiorentina', name: 'ACF Fiorentina', file: 'acf-fiorentina.png' },
  { id: 'as-roma', name: 'AS Roma', file: 'as-roma.png' },
  { id: 'atalanta-bc', name: 'Atalanta BC', file: 'atalanta-bc.png' },
  { id: 'bologna-fc-1909', name: 'Bologna FC 1909', file: 'bologna-fc-1909.png' },
  { id: 'cagliari-calcio', name: 'Cagliari Calcio', file: 'cagliari-calcio.png' },
  { id: 'como-1907', name: 'Como 1907', file: 'como-1907.png' },
  { id: 'genoa-cfc', name: 'Genoa CFC', file: 'genoa-cfc.png' },
  { id: 'hellas-verona', name: 'Hellas Verona', file: 'hellas-verona.png' },
  { id: 'inter-milan', name: 'Inter Milan', file: 'inter-milan.png' },
  { id: 'juventus-fc', name: 'Juventus FC', file: 'juventus-fc.png' },
  { id: 'parma-calcio-1913', name: 'Parma Calcio 1913', file: 'parma-calcio-1913.png' },
  { id: 'pisa-sporting-club', name: 'Pisa Sporting Club', file: 'pisa-sporting-club.png' },
  { id: 'ss-lazio', name: 'SS Lazio', file: 'ss-lazio.png' },
  { id: 'ssc-napoli', name: 'SSC Napoli', file: 'ssc-napoli.png' },
  { id: 'torino-fc', name: 'Torino FC', file: 'torino-fc.png' },
  { id: 'us-cremonese', name: 'US Cremonese', file: 'us-cremonese.png' },
  { id: 'us-lecce', name: 'US Lecce', file: 'us-lecce.png' },
  { id: 'us-sassuolo', name: 'US Sassuolo', file: 'us-sassuolo.png' },
  { id: 'udinese-calcio', name: 'Udinese Calcio', file: 'udinese-calcio.png' },
  // Netherlands - Eredivisie
  { id: 'az-alkmaar', name: 'AZ Alkmaar', file: 'az-alkmaar.png' },
  { id: 'ajax-amsterdam', name: 'Ajax Amsterdam', file: 'ajax-amsterdam.png' },
  { id: 'excelsior-rotterdam', name: 'Excelsior Rotterdam', file: 'excelsior-rotterdam.png' },
  { id: 'fc-groningen', name: 'FC Groningen', file: 'fc-groningen.png' },
  { id: 'fc-utrecht', name: 'FC Utrecht', file: 'fc-utrecht.png' },
  { id: 'fc-volendam', name: 'FC Volendam', file: 'fc-volendam.png' },
  { id: 'feyenoord-rotterdam', name: 'Feyenoord Rotterdam', file: 'feyenoord-rotterdam.png' },
  { id: 'fortuna-sittard', name: 'Fortuna Sittard', file: 'fortuna-sittard.png' },
  { id: 'go-ahead-eagles', name: 'Go Ahead Eagles', file: 'go-ahead-eagles.png' },
  { id: 'heracles-almelo', name: 'Heracles Almelo', file: 'heracles-almelo.png' },
  { id: 'nac-breda', name: 'NAC Breda', file: 'nac-breda.png' },
  { id: 'nec-nijmegen', name: 'NEC Nijmegen', file: 'nec-nijmegen.png' },
  { id: 'pec-zwolle', name: 'PEC Zwolle', file: 'pec-zwolle.png' },
  { id: 'psv-eindhoven', name: 'PSV Eindhoven', file: 'psv-eindhoven.png' },
  { id: 'sc-heerenveen', name: 'SC Heerenveen', file: 'sc-heerenveen.png' },
  { id: 'sc-telstar', name: 'SC Telstar', file: 'sc-telstar.png' },
  { id: 'sparta-rotterdam', name: 'Sparta Rotterdam', file: 'sparta-rotterdam.png' },
  { id: 'twente-enschede-fc', name: 'Twente Enschede FC', file: 'twente-enschede-fc.png' },
  // Norway - Eliteserien
  { id: 'bryne-fk', name: 'Bryne FK', file: 'bryne-fk.png' },
  { id: 'fk-bod-glimt', name: 'FK Bodø/Glimt', file: 'fk-bod-glimt.png' },
  { id: 'fk-haugesund', name: 'FK Haugesund', file: 'fk-haugesund.png' },
  { id: 'fredrikstad-fk', name: 'Fredrikstad FK', file: 'fredrikstad-fk.png' },
  { id: 'hamarkameratene', name: 'Hamarkameratene', file: 'hamarkameratene.png' },
  { id: 'kfum-kameratene-oslo', name: 'KFUM-Kameratene Oslo', file: 'kfum-kameratene-oslo.png' },
  { id: 'kristiansund-bk', name: 'Kristiansund BK', file: 'kristiansund-bk.png' },
  { id: 'molde-fk', name: 'Molde FK', file: 'molde-fk.png' },
  { id: 'rosenborg-bk', name: 'Rosenborg BK', file: 'rosenborg-bk.png' },
  { id: 'sk-brann', name: 'SK Brann', file: 'sk-brann.png' },
  { id: 'sandefjord-fotball', name: 'Sandefjord Fotball', file: 'sandefjord-fotball.png' },
  { id: 'sarpsborg-08-ff', name: 'Sarpsborg 08 FF', file: 'sarpsborg-08-ff.png' },
  { id: 'str-msgodset-if', name: 'Strømsgodset IF', file: 'str-msgodset-if.png' },
  { id: 'troms-il', name: 'Tromsø IL', file: 'troms-il.png' },
  { id: 'viking-fk', name: 'Viking FK', file: 'viking-fk.png' },
  { id: 'valerenga-fotball-elite', name: 'Vålerenga Fotball Elite', file: 'valerenga-fotball-elite.png' },
  // Poland - PKO BP Ekstraklasa
  { id: 'arka-gdynia', name: 'Arka Gdynia', file: 'arka-gdynia.png' },
  { id: 'bruk-bet-termalica-nieciecza', name: 'Bruk-Bet Termalica Nieciecza', file: 'bruk-bet-termalica-nieciecza.png' },
  { id: 'cracovia', name: 'Cracovia', file: 'cracovia.png' },
  { id: 'gks-katowice', name: 'GKS Katowice', file: 'gks-katowice.png' },
  { id: 'gornik-zabrze', name: 'Górnik Zabrze', file: 'gornik-zabrze.png' },
  { id: 'jagiellonia-bialystok', name: 'Jagiellonia Bialystok', file: 'jagiellonia-bialystok.png' },
  { id: 'korona-kielce', name: 'Korona Kielce', file: 'korona-kielce.png' },
  { id: 'lech-poznan', name: 'Lech Poznan', file: 'lech-poznan.png' },
  { id: 'lechia-gdansk', name: 'Lechia Gdansk', file: 'lechia-gdansk.png' },
  { id: 'legia-warszawa', name: 'Legia Warszawa', file: 'legia-warszawa.png' },
  { id: 'motor-lublin', name: 'Motor Lublin', file: 'motor-lublin.png' },
  { id: 'piast-gliwice', name: 'Piast Gliwice', file: 'piast-gliwice.png' },
  { id: 'pogon-szczecin', name: 'Pogon Szczecin', file: 'pogon-szczecin.png' },
  { id: 'radomiak-radom', name: 'Radomiak Radom', file: 'radomiak-radom.png' },
  { id: 'rakow-cz-stochowa', name: 'Raków Częstochowa', file: 'rakow-cz-stochowa.png' },
  { id: 'widzew-lodz', name: 'Widzew Lodz', file: 'widzew-lodz.png' },
  { id: 'wisla-plock', name: 'Wisla Plock', file: 'wisla-plock.png' },
  { id: 'zaglebie-lubin', name: 'Zaglebie Lubin', file: 'zaglebie-lubin.png' },
  // Portugal - Liga Portugal
  { id: 'avs-futebol', name: 'Avs Futebol', file: 'avs-futebol.png' },
  { id: 'cd-nacional', name: 'CD Nacional', file: 'cd-nacional.png' },
  { id: 'cd-santa-clara', name: 'CD Santa Clara', file: 'cd-santa-clara.png' },
  { id: 'cd-tondela', name: 'CD Tondela', file: 'cd-tondela.png' },
  { id: 'cf-estrela-amadora', name: 'CF Estrela Amadora', file: 'cf-estrela-amadora.png' },
  { id: 'casa-pia-ac', name: 'Casa Pia AC', file: 'casa-pia-ac.png' },
  { id: 'fc-alverca', name: 'FC Alverca', file: 'fc-alverca.png' },
  { id: 'fc-arouca', name: 'FC Arouca', file: 'fc-arouca.png' },
  { id: 'fc-famalicao', name: 'FC Famalicão', file: 'fc-famalicao.png' },
  { id: 'fc-porto', name: 'FC Porto', file: 'fc-porto.png' },
  { id: 'gd-estoril-praia', name: 'GD Estoril Praia', file: 'gd-estoril-praia.png' },
  { id: 'gil-vicente-fc', name: 'Gil Vicente FC', file: 'gil-vicente-fc.png' },
  { id: 'moreirense-fc', name: 'Moreirense FC', file: 'moreirense-fc.png' },
  { id: 'rio-ave-fc', name: 'Rio Ave FC', file: 'rio-ave-fc.png' },
  { id: 'sc-braga', name: 'SC Braga', file: 'sc-braga.png' },
  { id: 'sl-benfica', name: 'SL Benfica', file: 'sl-benfica.png' },
  { id: 'sporting-cp', name: 'Sporting CP', file: 'sporting-cp.png' },
  { id: 'vitoria-guimaraes-sc', name: 'Vitória Guimarães SC', file: 'vitoria-guimaraes-sc.png' },
  // Romania - SuperLiga
  { id: 'acsc-fc-arges', name: 'ACSC FC Arges', file: 'acsc-fc-arges.png' },
  { id: 'afc-unirea-04-slobozia', name: 'AFC Unirea 04 Slobozia', file: 'afc-unirea-04-slobozia.png' },
  { id: 'afk-csikszereda-miercurea-ciuc', name: 'AFK Csikszereda Miercurea Ciuc', file: 'afk-csikszereda-miercurea-ciuc.png' },
  { id: 'cfr-cluj', name: 'CFR Cluj', file: 'cfr-cluj.png' },
  { id: 'cs-universitatea-craiova', name: 'CS Universitatea Craiova', file: 'cs-universitatea-craiova.png' },
  { id: 'fc-botosani', name: 'FC Botosani', file: 'fc-botosani.png' },
  { id: 'fc-dinamo-1948', name: 'FC Dinamo 1948', file: 'fc-dinamo-1948.png' },
  { id: 'fc-hermannstadt', name: 'FC Hermannstadt', file: 'fc-hermannstadt.png' },
  { id: 'fc-metaloglobus-bucharest', name: 'FC Metaloglobus Bucharest', file: 'fc-metaloglobus-bucharest.png' },
  { id: 'fc-rapid-1923', name: 'FC Rapid 1923', file: 'fc-rapid-1923.png' },
  { id: 'fc-universitatea-cluj', name: 'FC Universitatea Cluj', file: 'fc-universitatea-cluj.png' },
  { id: 'fcsb', name: 'FCSB', file: 'fcsb.png' },
  { id: 'fcv-farul-constanta', name: 'FCV Farul Constanta', file: 'fcv-farul-constanta.png' },
  { id: 'petrolul-ploiesti', name: 'Petrolul Ploiesti', file: 'petrolul-ploiesti.png' },
  { id: 'sc-otelul-galati', name: 'SC Otelul Galati', file: 'sc-otelul-galati.png' },
  { id: 'uta-arad', name: 'UTA Arad', file: 'uta-arad.png' },
  // Russia - Premier Liga
  { id: 'akhmat-grozny', name: 'Akhmat Grozny', file: 'akhmat-grozny.png' },
  { id: 'akron-togliatti', name: 'Akron Togliatti', file: 'akron-togliatti.png' },
  { id: 'baltika-kaliningrad', name: 'Baltika Kaliningrad', file: 'baltika-kaliningrad.png' },
  { id: 'cska-moscow', name: 'CSKA Moscow', file: 'cska-moscow.png' },
  { id: 'dinamo-makhachkala', name: 'Dinamo Makhachkala', file: 'dinamo-makhachkala.png' },
  { id: 'dynamo-moscow', name: 'Dynamo Moscow', file: 'dynamo-moscow.png' },
  { id: 'fc-krasnodar', name: 'FC Krasnodar', file: 'fc-krasnodar.png' },
  { id: 'fc-pari-nizhniy-novgorod', name: 'FC Pari Nizhniy Novgorod', file: 'fc-pari-nizhniy-novgorod.png' },
  { id: 'fc-rostov', name: 'FC Rostov', file: 'fc-rostov.png' },
  { id: 'fc-sochi', name: 'FC Sochi', file: 'fc-sochi.png' },
  { id: 'krylya-sovetov-samara', name: 'Krylya Sovetov Samara', file: 'krylya-sovetov-samara.png' },
  { id: 'lokomotiv-moscow', name: 'Lokomotiv Moscow', file: 'lokomotiv-moscow.png' },
  { id: 'rubin-kazan', name: 'Rubin Kazan', file: 'rubin-kazan.png' },
  { id: 'spartak-moscow', name: 'Spartak Moscow', file: 'spartak-moscow.png' },
  { id: 'torpedo-moscow', name: 'Torpedo Moscow', file: 'torpedo-moscow.png' },
  { id: 'zenit-st-petersburg', name: 'Zenit St. Petersburg', file: 'zenit-st-petersburg.png' },
  // Scotland - Scottish Premiership
  { id: 'aberdeen-fc', name: 'Aberdeen FC', file: 'aberdeen-fc.png' },
  { id: 'celtic-fc', name: 'Celtic FC', file: 'celtic-fc.png' },
  { id: 'dundee-fc', name: 'Dundee FC', file: 'dundee-fc.png' },
  { id: 'dundee-united-fc', name: 'Dundee United FC', file: 'dundee-united-fc.png' },
  { id: 'falkirk-fc', name: 'Falkirk FC', file: 'falkirk-fc.png' },
  { id: 'heart-of-midlothian-fc', name: 'Heart of Midlothian FC', file: 'heart-of-midlothian-fc.png' },
  { id: 'hibernian-fc', name: 'Hibernian FC', file: 'hibernian-fc.png' },
  { id: 'kilmarnock-fc', name: 'Kilmarnock FC', file: 'kilmarnock-fc.png' },
  { id: 'livingston-fc', name: 'Livingston FC', file: 'livingston-fc.png' },
  { id: 'motherwell-fc', name: 'Motherwell FC', file: 'motherwell-fc.png' },
  { id: 'rangers-fc', name: 'Rangers FC', file: 'rangers-fc.png' },
  { id: 'st-mirren-fc', name: 'St. Mirren FC', file: 'st-mirren-fc.png' },
  // Serbia - Super liga Srbije
  { id: 'fk-cukaricki', name: 'FK Cukaricki', file: 'fk-cukaricki.png' },
  { id: 'fk-imt-belgrad', name: 'FK IMT Belgrad', file: 'fk-imt-belgrad.png' },
  { id: 'fk-javor-matis-ivanjica', name: 'FK Javor-Matis Ivanjica', file: 'fk-javor-matis-ivanjica.png' },
  { id: 'fk-mladost-lucani', name: 'FK Mladost Lucani', file: 'fk-mladost-lucani.png' },
  { id: 'fk-napredak-krusevac', name: 'FK Napredak Krusevac', file: 'fk-napredak-krusevac.png' },
  { id: 'fk-novi-pazar', name: 'FK Novi Pazar', file: 'fk-novi-pazar.png' },
  { id: 'fk-partizan-belgrade', name: 'FK Partizan Belgrade', file: 'fk-partizan-belgrade.png' },
  { id: 'fk-radnicki-1923-kragujevac', name: 'FK Radnicki 1923 Kragujevac', file: 'fk-radnicki-1923-kragujevac.png' },
  { id: 'fk-radnicki-nis', name: 'FK Radnicki Nis', file: 'fk-radnicki-nis.png' },
  { id: 'fk-radnik-surdulica', name: 'FK Radnik Surdulica', file: 'fk-radnik-surdulica.png' },
  { id: 'fk-spartak-subotica', name: 'FK Spartak Subotica', file: 'fk-spartak-subotica.png' },
  { id: 'fk-tsc-backa-topola', name: 'FK TSC Backa Topola', file: 'fk-tsc-backa-topola.png' },
  { id: 'fk-vojvodina-novi-sad', name: 'FK Vojvodina Novi Sad', file: 'fk-vojvodina-novi-sad.png' },
  { id: 'ofk-beograd', name: 'OFK Beograd', file: 'ofk-beograd.png' },
  { id: 'red-star-belgrade', name: 'Red Star Belgrade', file: 'red-star-belgrade.png' },
  { id: 'zeleznicar-pancevo', name: 'Zeleznicar Pancevo', file: 'zeleznicar-pancevo.png' },
  // Spain - LaLiga
  { id: 'athletic-bilbao', name: 'Athletic Bilbao', file: 'athletic-bilbao.png' },
  { id: 'atletico-de-madrid', name: 'Atlético de Madrid', file: 'atletico-de-madrid.png' },
  { id: 'ca-osasuna', name: 'CA Osasuna', file: 'ca-osasuna.png' },
  { id: 'celta-de-vigo', name: 'Celta de Vigo', file: 'celta-de-vigo.png' },
  { id: 'deportivo-alaves', name: 'Deportivo Alavés', file: 'deportivo-alaves.png' },
  { id: 'elche-cf', name: 'Elche CF', file: 'elche-cf.png' },
  { id: 'fc-barcelona', name: 'FC Barcelona', file: 'fc-barcelona.png' },
  { id: 'getafe-cf', name: 'Getafe CF', file: 'getafe-cf.png' },
  { id: 'girona-fc', name: 'Girona FC', file: 'girona-fc.png' },
  { id: 'levante-ud', name: 'Levante UD', file: 'levante-ud.png' },
  { id: 'rcd-espanyol-barcelona', name: 'RCD Espanyol Barcelona', file: 'rcd-espanyol-barcelona.png' },
  { id: 'rcd-mallorca', name: 'RCD Mallorca', file: 'rcd-mallorca.png' },
  { id: 'rayo-vallecano', name: 'Rayo Vallecano', file: 'rayo-vallecano.png' },
  { id: 'real-betis-balompie', name: 'Real Betis Balompié', file: 'real-betis-balompie.png' },
  { id: 'real-madrid', name: 'Real Madrid', file: 'real-madrid.png' },
  { id: 'real-oviedo', name: 'Real Oviedo', file: 'real-oviedo.png' },
  { id: 'real-sociedad', name: 'Real Sociedad', file: 'real-sociedad.png' },
  { id: 'sevilla-fc', name: 'Sevilla FC', file: 'sevilla-fc.png' },
  { id: 'valencia-cf', name: 'Valencia CF', file: 'valencia-cf.png' },
  { id: 'villarreal-cf', name: 'Villarreal CF', file: 'villarreal-cf.png' },
  // Sweden - Allsvenskan
  { id: 'aik', name: 'AIK', file: 'aik.png' },
  { id: 'bk-hacken', name: 'BK Häcken', file: 'bk-hacken.png' },
  { id: 'degerfors-if', name: 'Degerfors IF', file: 'degerfors-if.png' },
  { id: 'djurgardens-if', name: 'Djurgårdens IF', file: 'djurgardens-if.png' },
  { id: 'gais', name: 'GAIS', file: 'gais.png' },
  { id: 'halmstads-bk', name: 'Halmstads BK', file: 'halmstads-bk.png' },
  { id: 'hammarby-if', name: 'Hammarby IF', file: 'hammarby-if.png' },
  { id: 'if-brommapojkarna', name: 'IF Brommapojkarna', file: 'if-brommapojkarna.png' },
  { id: 'if-elfsborg', name: 'IF Elfsborg', file: 'if-elfsborg.png' },
  { id: 'ifk-goteborg', name: 'IFK Göteborg', file: 'ifk-goteborg.png' },
  { id: 'ifk-norrkoping', name: 'IFK Norrköping', file: 'ifk-norrkoping.png' },
  { id: 'ifk-varnamo', name: 'IFK Värnamo', file: 'ifk-varnamo.png' },
  { id: 'ik-sirius', name: 'IK Sirius', file: 'ik-sirius.png' },
  { id: 'malmo-ff', name: 'Malmö FF', file: 'malmo-ff.png' },
  { id: 'mjallby-aif', name: 'Mjällby AIF', file: 'mjallby-aif.png' },
  { id: 'osters-if', name: 'Östers IF', file: 'osters-if.png' },
  // Switzerland - Super League
  { id: 'bsc-young-boys', name: 'BSC Young Boys', file: 'bsc-young-boys.png' },
  { id: 'fc-basel-1893', name: 'FC Basel 1893', file: 'fc-basel-1893.png' },
  { id: 'fc-lausanne-sport', name: 'FC Lausanne-Sport', file: 'fc-lausanne-sport.png' },
  { id: 'fc-lugano', name: 'FC Lugano', file: 'fc-lugano.png' },
  { id: 'fc-luzern', name: 'FC Luzern', file: 'fc-luzern.png' },
  { id: 'fc-sion', name: 'FC Sion', file: 'fc-sion.png' },
  { id: 'fc-st-gallen-1879', name: 'FC St. Gallen 1879', file: 'fc-st-gallen-1879.png' },
  { id: 'fc-thun', name: 'FC Thun', file: 'fc-thun.png' },
  { id: 'fc-winterthur', name: 'FC Winterthur', file: 'fc-winterthur.png' },
  { id: 'fc-zurich', name: 'FC Zürich', file: 'fc-zurich.png' },
  { id: 'grasshopper-club-zurich', name: 'Grasshopper Club Zurich', file: 'grasshopper-club-zurich.png' },
  { id: 'servette-fc', name: 'Servette FC', file: 'servette-fc.png' },
  // Türkiye - Süper Lig
  { id: 'alanyaspor', name: 'Alanyaspor', file: 'alanyaspor.png' },
  { id: 'antalyaspor', name: 'Antalyaspor', file: 'antalyaspor.png' },
  { id: 'basaksehir-fk', name: 'Basaksehir FK', file: 'basaksehir-fk.png' },
  { id: 'besiktas-jk', name: 'Besiktas JK', file: 'besiktas-jk.png' },
  { id: 'caykur-rizespor', name: 'Caykur Rizespor', file: 'caykur-rizespor.png' },
  { id: 'eyupspor', name: 'Eyüpspor', file: 'eyupspor.png' },
  { id: 'fatih-karagumruk', name: 'Fatih Karagümrük', file: 'fatih-karagumruk.png' },
  { id: 'fenerbahce', name: 'Fenerbahce', file: 'fenerbahce.png' },
  { id: 'galatasaray', name: 'Galatasaray', file: 'galatasaray.png' },
  { id: 'gaziantep-fk', name: 'Gaziantep FK', file: 'gaziantep-fk.png' },
  { id: 'genclerbirligi-ankara', name: 'Genclerbirligi Ankara', file: 'genclerbirligi-ankara.png' },
  { id: 'goztepe', name: 'Göztepe', file: 'goztepe.png' },
  { id: 'kasimpasa', name: 'Kasimpasa', file: 'kasimpasa.png' },
  { id: 'kayserispor', name: 'Kayserispor', file: 'kayserispor.png' },
  { id: 'kocaelispor', name: 'Kocaelispor', file: 'kocaelispor.png' },
  { id: 'konyaspor', name: 'Konyaspor', file: 'konyaspor.png' },
  { id: 'samsunspor', name: 'Samsunspor', file: 'samsunspor.png' },
  { id: 'trabzonspor', name: 'Trabzonspor', file: 'trabzonspor.png' },
  // Ukraine - Premier Liga
  { id: 'dynamo-kyiv', name: 'Dynamo Kyiv', file: 'dynamo-kyiv.png' },
  { id: 'epicentr-kamyanets-podilskyi', name: 'Epicentr Kamyanets-Podilskyi', file: 'epicentr-kamyanets-podilskyi.png' },
  { id: 'fc-kudrivka', name: 'FC Kudrivka', file: 'fc-kudrivka.png' },
  { id: 'fc-oleksandriya', name: 'FC Oleksandriya', file: 'fc-oleksandriya.png' },
  { id: 'karpaty-lviv', name: 'Karpaty Lviv', file: 'karpaty-lviv.png' },
  { id: 'kolos-kovalivka', name: 'Kolos Kovalivka', file: 'kolos-kovalivka.png' },
  { id: 'kryvbas-kryvyi-rig', name: 'Kryvbas Kryvyi Rig', file: 'kryvbas-kryvyi-rig.png' },
  { id: 'lnz-cherkasy', name: 'LNZ Cherkasy', file: 'lnz-cherkasy.png' },
  { id: 'metalist-1925-kharkiv', name: 'Metalist 1925 Kharkiv', file: 'metalist-1925-kharkiv.png' },
  { id: 'nk-veres-rivne', name: 'NK Veres Rivne', file: 'nk-veres-rivne.png' },
  { id: 'obolon-kyiv', name: 'Obolon Kyiv', file: 'obolon-kyiv.png' },
  { id: 'polissya-zhytomyr', name: 'Polissya Zhytomyr', file: 'polissya-zhytomyr.png' },
  { id: 'rukh-lviv', name: 'Rukh Lviv', file: 'rukh-lviv.png' },
  { id: 'sc-poltava', name: 'SC Poltava', file: 'sc-poltava.png' },
  { id: 'shakhtar-donetsk', name: 'Shakhtar Donetsk', file: 'shakhtar-donetsk.png' },
  { id: 'zorya-lugansk', name: 'Zorya Lugansk', file: 'zorya-lugansk.png' },
]

export function getClub(id: string | null | undefined): Club | undefined {
  if (!id) return undefined
  return CLUBS.find((c) => c.id === id)
}

export interface Country {
  code: string
  name: string
  flag: string
}

export const COUNTRIES: Country[] = [
  { code: 'AF', name: 'Afghanistan', flag: '🇦🇫' },
  { code: 'AL', name: 'Albania', flag: '🇦🇱' },
  { code: 'DZ', name: 'Algeria', flag: '🇩🇿' },
  { code: 'AR', name: 'Argentina', flag: '🇦🇷' },
  { code: 'AM', name: 'Armenia', flag: '🇦🇲' },
  { code: 'AU', name: 'Australia', flag: '🇦🇺' },
  { code: 'AT', name: 'Austria', flag: '🇦🇹' },
  { code: 'AZ', name: 'Azerbaijan', flag: '🇦🇿' },
  { code: 'BH', name: 'Bahrain', flag: '🇧🇭' },
  { code: 'BD', name: 'Bangladesh', flag: '🇧🇩' },
  { code: 'BY', name: 'Belarus', flag: '🇧🇾' },
  { code: 'BE', name: 'Belgium', flag: '🇧🇪' },
  { code: 'BO', name: 'Bolivia', flag: '🇧🇴' },
  { code: 'BA', name: 'Bosnia and Herzegovina', flag: '🇧🇦' },
  { code: 'BR', name: 'Brazil', flag: '🇧🇷' },
  { code: 'BG', name: 'Bulgaria', flag: '🇧🇬' },
  { code: 'CM', name: 'Cameroon', flag: '🇨🇲' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦' },
  { code: 'CL', name: 'Chile', flag: '🇨🇱' },
  { code: 'CN', name: 'China', flag: '🇨🇳' },
  { code: 'CO', name: 'Colombia', flag: '🇨🇴' },
  { code: 'HR', name: 'Croatia', flag: '🇭🇷' },
  { code: 'CU', name: 'Cuba', flag: '🇨🇺' },
  { code: 'CY', name: 'Cyprus', flag: '🇨🇾' },
  { code: 'CZ', name: 'Czechia', flag: '🇨🇿' },
  { code: 'DK', name: 'Denmark', flag: '🇩🇰' },
  { code: 'EC', name: 'Ecuador', flag: '🇪🇨' },
  { code: 'EG', name: 'Egypt', flag: '🇪🇬' },
  { code: 'GB-ENG', name: 'England', flag: '🇬🇧' },
  { code: 'EE', name: 'Estonia', flag: '🇪🇪' },
  { code: 'ET', name: 'Ethiopia', flag: '🇪🇹' },
  { code: 'FI', name: 'Finland', flag: '🇫🇮' },
  { code: 'FR', name: 'France', flag: '🇫🇷' },
  { code: 'GE', name: 'Georgia', flag: '🇬🇪' },
  { code: 'DE', name: 'Germany', flag: '🇩🇪' },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭' },
  { code: 'GR', name: 'Greece', flag: '🇬🇷' },
  { code: 'HU', name: 'Hungary', flag: '🇭🇺' },
  { code: 'IS', name: 'Iceland', flag: '🇮🇸' },
  { code: 'IN', name: 'India', flag: '🇮🇳' },
  { code: 'ID', name: 'Indonesia', flag: '🇮🇩' },
  { code: 'IR', name: 'Iran', flag: '🇮🇷' },
  { code: 'IQ', name: 'Iraq', flag: '🇮🇶' },
  { code: 'IE', name: 'Ireland', flag: '🇮🇪' },
  { code: 'IL', name: 'Israel', flag: '🇮🇱' },
  { code: 'IT', name: 'Italy', flag: '🇮🇹' },
  { code: 'CI', name: 'Ivory Coast', flag: '🇨🇮' },
  { code: 'JM', name: 'Jamaica', flag: '🇯🇲' },
  { code: 'JP', name: 'Japan', flag: '🇯🇵' },
  { code: 'JO', name: 'Jordan', flag: '🇯🇴' },
  { code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿' },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪' },
  { code: 'XK', name: 'Kosovo', flag: '🇽🇰' },
  { code: 'KW', name: 'Kuwait', flag: '🇰🇼' },
  { code: 'LV', name: 'Latvia', flag: '🇱🇻' },
  { code: 'LB', name: 'Lebanon', flag: '🇱🇧' },
  { code: 'LY', name: 'Libya', flag: '🇱🇾' },
  { code: 'LT', name: 'Lithuania', flag: '🇱🇹' },
  { code: 'LU', name: 'Luxembourg', flag: '🇱🇺' },
  { code: 'MY', name: 'Malaysia', flag: '🇲🇾' },
  { code: 'ML', name: 'Mali', flag: '🇲🇱' },
  { code: 'MT', name: 'Malta', flag: '🇲🇹' },
  { code: 'MX', name: 'Mexico', flag: '🇲🇽' },
  { code: 'MD', name: 'Moldova', flag: '🇲🇩' },
  { code: 'ME', name: 'Montenegro', flag: '🇲🇪' },
  { code: 'MA', name: 'Morocco', flag: '🇲🇦' },
  { code: 'NP', name: 'Nepal', flag: '🇳🇵' },
  { code: 'NL', name: 'Netherlands', flag: '🇳🇱' },
  { code: 'NZ', name: 'New Zealand', flag: '🇳🇿' },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬' },
  { code: 'MK', name: 'North Macedonia', flag: '🇲🇰' },
  { code: 'GB-NIR', name: 'Northern Ireland', flag: '🇬🇧' },
  { code: 'NO', name: 'Norway', flag: '🇳🇴' },
  { code: 'OM', name: 'Oman', flag: '🇴🇲' },
  { code: 'PK', name: 'Pakistan', flag: '🇵🇰' },
  { code: 'PS', name: 'Palestine', flag: '🇵🇸' },
  { code: 'PA', name: 'Panama', flag: '🇵🇦' },
  { code: 'PY', name: 'Paraguay', flag: '🇵🇾' },
  { code: 'PE', name: 'Peru', flag: '🇵🇪' },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭' },
  { code: 'PL', name: 'Poland', flag: '🇵🇱' },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹' },
  { code: 'QA', name: 'Qatar', flag: '🇶🇦' },
  { code: 'RO', name: 'Romania', flag: '🇷🇴' },
  { code: 'RU', name: 'Russia', flag: '🇷🇺' },
  { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦' },
  { code: 'GB-SCT', name: 'Scotland', flag: '🇬🇧' },
  { code: 'SN', name: 'Senegal', flag: '🇸🇳' },
  { code: 'RS', name: 'Serbia', flag: '🇷🇸' },
  { code: 'SG', name: 'Singapore', flag: '🇸🇬' },
  { code: 'SK', name: 'Slovakia', flag: '🇸🇰' },
  { code: 'SI', name: 'Slovenia', flag: '🇸🇮' },
  { code: 'SO', name: 'Somalia', flag: '🇸🇴' },
  { code: 'ZA', name: 'South Africa', flag: '🇿🇦' },
  { code: 'KR', name: 'South Korea', flag: '🇰🇷' },
  { code: 'SS', name: 'South Sudan', flag: '🇸🇸' },
  { code: 'ES', name: 'Spain', flag: '🇪🇸' },
  { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰' },
  { code: 'SD', name: 'Sudan', flag: '🇸🇩' },
  { code: 'SE', name: 'Sweden', flag: '🇸🇪' },
  { code: 'CH', name: 'Switzerland', flag: '🇨🇭' },
  { code: 'SY', name: 'Syria', flag: '🇸🇾' },
  { code: 'TH', name: 'Thailand', flag: '🇹🇭' },
  { code: 'TN', name: 'Tunisia', flag: '🇹🇳' },
  { code: 'TR', name: 'Turkey', flag: '🇹🇷' },
  { code: 'TM', name: 'Turkmenistan', flag: '🇹🇲' },
  { code: 'UG', name: 'Uganda', flag: '🇺🇬' },
  { code: 'UA', name: 'Ukraine', flag: '🇺🇦' },
  { code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪' },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧' },
  { code: 'US', name: 'United States', flag: '🇺🇸' },
  { code: 'UY', name: 'Uruguay', flag: '🇺🇾' },
  { code: 'UZ', name: 'Uzbekistan', flag: '🇺🇿' },
  { code: 'VE', name: 'Venezuela', flag: '🇻🇪' },
  { code: 'VN', name: 'Vietnam', flag: '🇻🇳' },
  { code: 'GB-WLS', name: 'Wales', flag: '🇬🇧' },
  { code: 'YE', name: 'Yemen', flag: '🇾🇪' },
  { code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼' },
]

export function getCountry(code: string | null | undefined): Country | undefined {
  if (!code) return undefined
  return COUNTRIES.find((c) => c.code === code)
}
